import type { VendorInput } from "./vendor-types";

export const SAMPLE_VENDORS: VendorInput[] = [
  // Photography & Videography
  { vendor_name: "Cupcake Productions", category: "Photography & Videography", subcategory: "Candid Photography", location: "Delhi", contact_number: "+91 98100 23456", email: "hello@cupcakeprod.in", instagram_handle: "cupcakeproductions", website: "cupcakeproductions.com", google_rating: 4.8, price_text: "On discussion", commission_model: "10%", portfolio_link: "cupcakeproductions.com/portfolio", source: "Sample Data", remarks: "Premium choice for celebrity weddings", number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: "Photo + Video + Album", team_size: "8 person crew", deliverables: "500+ edited photos, 8 min film" },
  { vendor_name: "Israni Photography", category: "Photography & Videography", subcategory: "Documentary Style", location: "Gurugram", contact_number: "+91 98201 34567", email: "info@israni.in", instagram_handle: "israniphotography", website: "israni.in", google_rating: 4.9, price_text: "On discussion", commission_model: "On discussion", source: "Sample Data", remarks: "Multi-city teams available", portfolio_link: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: "10-12", deliverables: null },
  { vendor_name: "Lensgram Studios", category: "Photography & Videography", subcategory: "Pre-wedding shoots", location: "Noida", contact_number: "+91 99100 11223", email: "team@lensgram.in", instagram_handle: "lensgram", google_rating: 4.5, price_text: "On discussion", commission_model: "15%", source: "Sample Data", website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Decor
  { vendor_name: "Devika Narain & Co", category: "Decor", subcategory: "Floral Design", location: "Pan India", contact_number: "+91 98990 12345", email: "studio@devikanarain.com", instagram_handle: "devikanarain", website: "devikanarain.com", google_rating: 4.9, price_text: "On discussion", commission_model: "Included in quote", source: "Sample Data", remarks: "Top-tier celebrity decor", portfolio_link: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "FNP Weddings", category: "Decor", location: "Delhi", contact_number: "+91 98765 11122", email: "weddings@fnp.com", instagram_handle: "fnpweddings", website: "fnpweddings.com", google_rating: 4.4, price_text: "On discussion", commission_model: "12%", source: "Sample Data", subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "The Wedding Salad", category: "Decor", location: "Gurugram", contact_number: "+91 99100 88990", instagram_handle: "theweddingsalad", google_rating: 4.6, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Catering
  { vendor_name: "Foodlink", category: "Catering", subcategory: "Multi-cuisine", location: "Delhi", contact_number: "+91 98101 22334", email: "delhi@foodlink.in", instagram_handle: "foodlinkcaterers", google_rating: 4.7, price_text: "On discussion", commission_model: "10% on plate cost", source: "Sample Data", remarks: "Per plate pricing", website: null, portfolio_link: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Galaxy Group Caterers", category: "Catering", location: "Gurugram", contact_number: "+91 98765 33445", google_rating: 4.5, price_text: "On discussion", commission_model: "12%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Tonino Catering", category: "Catering", subcategory: "Italian/Continental", location: "Noida", contact_number: "+91 99110 22334", instagram_handle: "toninocatering", google_rating: 4.6, price_text: "On discussion", commission_model: "On discussion", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Sound & Lighting
  { vendor_name: "Modern Stage Service", category: "Sound & Lighting", location: "Delhi", contact_number: "+91 98101 44556", google_rating: 4.4, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Sound Affair", category: "Sound & Lighting", location: "Gurugram", contact_number: "+91 98760 55667", instagram_handle: "soundaffairindia", google_rating: 4.6, price_text: "On discussion", commission_model: "10%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Bright Light Productions", category: "Sound & Lighting", location: "Noida", contact_number: "+91 99110 66778", google_rating: 4.3, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Production & Event Management
  { vendor_name: "Wedniksha", category: "Production & Event Management", location: "Pan India", contact_number: "+91 98200 11223", email: "info@wedniksha.com", instagram_handle: "wedniksha", website: "wedniksha.com", google_rating: 4.7, price_text: "On discussion", commission_model: "10%", source: "Sample Data", subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Q Events", category: "Production & Event Management", location: "Delhi", contact_number: "+91 98101 99887", instagram_handle: "qeventsindia", google_rating: 4.5, price_text: "On discussion", commission_model: "12%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "ShaadiSquad Productions", category: "Production & Event Management", location: "Gurugram", contact_number: "+91 99100 33445", google_rating: 4.4, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // SFX
  { vendor_name: "Pyrocraft India", category: "Special Effects (SFX)", subcategory: "Cold pyro & confetti", location: "Delhi", contact_number: "+91 98101 77665", instagram_handle: "pyrocraftindia", google_rating: 4.5, price_text: "On discussion", commission_model: "On discussion", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Magic Moments SFX", category: "Special Effects (SFX)", location: "Gurugram", contact_number: "+91 98760 22334", google_rating: 4.3, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Sparkle FX Studio", category: "Special Effects (SFX)", subcategory: "Fireworks & lasers", location: "Noida", contact_number: "+91 99110 77889", instagram_handle: "sparklefxstudio", google_rating: 4.6, price_text: "On discussion", commission_model: "12%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Makeup
  { vendor_name: "Namrata Soni", category: "Makeup Artists", subcategory: "Bridal Makeup", location: "Delhi", contact_number: "+91 98100 88997", instagram_handle: "namratasoni", google_rating: 4.9, price_text: "On discussion", commission_model: "10%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Pooja Singh Makeup", category: "Makeup Artists", subcategory: "Bridal & Engagement", location: "Gurugram", contact_number: "+91 98760 33445", instagram_handle: "poojasinghmakeup", google_rating: 4.7, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Looksy By Aanchal", category: "Makeup Artists", location: "Noida", contact_number: "+91 99110 44556", instagram_handle: "looksybyaanchal", google_rating: 4.5, price_text: "On discussion", commission_model: "20%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Mehendi
  { vendor_name: "Veena Nagda", category: "Mehendi Artists", subcategory: "Bridal Mehendi", location: "Pan India", contact_number: "+91 98200 55443", instagram_handle: "veenanagdamehndi", google_rating: 4.9, price_text: "On discussion", commission_model: "On discussion", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Ash Kumar Mehendi", category: "Mehendi Artists", location: "Delhi", contact_number: "+91 98100 33221", instagram_handle: "ashkumarmehndi", google_rating: 4.7, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Henna By Riya", category: "Mehendi Artists", location: "Gurugram", contact_number: "+91 98760 99887", instagram_handle: "hennabyriya", google_rating: 4.4, price_text: "On discussion", commission_model: "20%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Hospitality & Manpower
  { vendor_name: "White Glove Services", category: "Hospitality & Manpower", subcategory: "Service staff", location: "Delhi", contact_number: "+91 98101 55667", google_rating: 4.5, price_text: "On discussion", commission_model: "10%", source: "Sample Data", remarks: "Per staff per day", email: null, instagram_handle: null, website: null, portfolio_link: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Royal Hospitality Group", category: "Hospitality & Manpower", location: "Gurugram", contact_number: "+91 98765 88990", google_rating: 4.4, price_text: "On discussion", commission_model: "12%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Elite Crew India", category: "Hospitality & Manpower", location: "Noida", contact_number: "+91 99100 22113", google_rating: 4.3, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Anchors & Emcees
  { vendor_name: "Cyrus Sahukar", category: "Anchors & Emcees", subcategory: "Celebrity Host", location: "Pan India", contact_number: "+91 98200 11225", instagram_handle: "cyrussahukar", google_rating: 4.8, price_text: "On discussion", commission_model: "On discussion", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Pranav Ghai", category: "Anchors & Emcees", location: "Delhi", contact_number: "+91 98100 66778", instagram_handle: "pranavghai", google_rating: 4.6, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Aanchal Anand", category: "Anchors & Emcees", location: "Gurugram", contact_number: "+91 98760 11334", instagram_handle: "aanchalanchor", google_rating: 4.5, price_text: "On discussion", commission_model: "20%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Car Rental & Transport
  { vendor_name: "Carzonrent", category: "Car Rental & Transport", location: "Delhi", contact_number: "+91 98101 11000", website: "carzonrent.com", google_rating: 4.3, price_text: "On discussion", commission_model: "10%", source: "Sample Data", remarks: "Per car per day", email: null, instagram_handle: null, subcategory: null, portfolio_link: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Avis Wedding Fleet", category: "Car Rental & Transport", subcategory: "Luxury cars", location: "Gurugram", contact_number: "+91 98765 22113", google_rating: 4.5, price_text: "On discussion", commission_model: "12%", source: "Sample Data", email: null, instagram_handle: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Royal Rides Noida", category: "Car Rental & Transport", location: "Noida", contact_number: "+91 99110 88776", google_rating: 4.2, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Hotels & Venues
  { vendor_name: "The Leela Palace, Jaipur", category: "Hotels & Venues", location: "Rajasthan", contact_number: "+91 14114 80000", website: "theleela.com", google_rating: 4.8, price_text: "On discussion", commission_model: "10%", source: "Sample Data", remarks: "Per room per night", number_of_rooms: 200, distance_from_delhi: "260 km / 4 hr drive", hotel_category: "Ultra-Luxury", email: null, instagram_handle: null, subcategory: null, portfolio_link: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "ITC Grand Bharat", category: "Hotels & Venues", location: "Gurugram", contact_number: "+91 12433 70000", website: "itchotels.com", google_rating: 4.7, price_text: "On discussion", commission_model: "12%", source: "Sample Data", number_of_rooms: 104, distance_from_delhi: "55 km / 1.5 hr drive", hotel_category: "Luxury", email: null, instagram_handle: null, subcategory: null, portfolio_link: null, remarks: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Taj Palace, New Delhi", category: "Hotels & Venues", location: "Delhi", contact_number: "+91 11663 30000", website: "tajhotels.com", google_rating: 4.7, price_text: "On discussion", commission_model: "10%", source: "Sample Data", number_of_rooms: 403, distance_from_delhi: "In Delhi", hotel_category: "Luxury", email: null, instagram_handle: null, subcategory: null, portfolio_link: null, remarks: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "The Westin Sohna", category: "Hotels & Venues", location: "Gurugram", contact_number: "+91 12410 40000", google_rating: 4.5, price_text: "On discussion", commission_model: "15%", source: "Sample Data", number_of_rooms: 130, distance_from_delhi: "65 km / 2 hr drive", hotel_category: "Upper Mid", email: null, instagram_handle: null, website: null, subcategory: null, portfolio_link: null, remarks: null, quote_breakdown: null, team_size: null, deliverables: null },

  // DJs & Live Music
  { vendor_name: "DJ Ganesh", category: "DJs & Live Music", subcategory: "Bollywood/EDM", location: "Delhi", contact_number: "+91 98100 99001", instagram_handle: "djganeshofficial", google_rating: 4.7, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Sufi Roots Band", category: "DJs & Live Music", subcategory: "Live Sufi music", location: "Gurugram", contact_number: "+91 98765 77665", instagram_handle: "sufirootsband", google_rating: 4.6, price_text: "On discussion", commission_model: "12%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "DJ Aakash", category: "DJs & Live Music", location: "Noida", contact_number: "+91 99110 33221", instagram_handle: "djaakashlive", google_rating: 4.4, price_text: "On discussion", commission_model: "20%", source: "Sample Data", email: null, website: null, subcategory: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },

  // Misc
  { vendor_name: "Wed Invites Co", category: "Miscellaneous", subcategory: "Invitations & Stationery", location: "Delhi", contact_number: "+91 98101 22556", instagram_handle: "wedinvitesco", google_rating: 4.5, price_text: "On discussion", commission_model: "15%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Petal Trail Florists", category: "Miscellaneous", subcategory: "Florists", location: "Gurugram", contact_number: "+91 98760 44332", instagram_handle: "petaltrail", google_rating: 4.4, price_text: "On discussion", commission_model: "12%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
  { vendor_name: "Sehra Couture", category: "Miscellaneous", subcategory: "Wedding Attire", location: "Delhi", contact_number: "+91 98101 99334", instagram_handle: "sehracouture", google_rating: 4.6, price_text: "On discussion", commission_model: "10%", source: "Sample Data", email: null, website: null, portfolio_link: null, remarks: null, number_of_rooms: null, distance_from_delhi: null, hotel_category: null, quote_breakdown: null, team_size: null, deliverables: null },
];
