/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorSignupRouteImport } from './routes/vendor-signup'
import { Route as VendorOnboardingRouteImport } from './routes/vendor-onboarding'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicVendorSignupRouteImport } from './routes/api/public/vendor-signup'
import { Route as ApiPublicInstagramImageRouteImport } from './routes/api/public/instagram-image'
import { Route as AdminProjectsIdRouteImport } from './routes/admin.projects.$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicVendorSignupCheckRouteImport } from './routes/api/public/vendor-signup.check'
import { Route as ApiFilesStreamSplatRouteImport } from './routes/api/files/stream.$'
import { Route as AdminProjectsIdPreviewClientIdRouteImport } from './routes/admin.projects.$id.preview.$clientId'

const VendorSignupRoute = VendorSignupRouteImport.update({
  id: '/vendor-signup',
  path: '/vendor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOnboardingRoute = VendorOnboardingRouteImport.update({
  id: '/vendor-onboarding',
  path: '/vendor-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVendorSignupRoute = ApiPublicVendorSignupRouteImport.update({
  id: '/api/public/vendor-signup',
  path: '/api/public/vendor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramImageRoute = ApiPublicInstagramImageRouteImport.update({
  id: '/api/public/instagram-image',
  path: '/api/public/instagram-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/admin/projects/$id',
  path: '/admin/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVendorSignupCheckRoute =
  ApiPublicVendorSignupCheckRouteImport.update({
    id: '/check',
    path: '/check',
    getParentRoute: () => ApiPublicVendorSignupRoute,
  } as any)
const ApiFilesStreamSplatRoute = ApiFilesStreamSplatRouteImport.update({
  id: '/api/files/stream/$',
  path: '/api/files/stream/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIdPreviewClientIdRoute =
  AdminProjectsIdPreviewClientIdRouteImport.update({
    id: '/preview/$clientId',
    path: '/preview/$clientId',
    getParentRoute: () => AdminProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor-onboarding': typeof VendorOnboardingRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/login': typeof ClientLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/projects/$id': typeof AdminProjectsIdRouteWithChildren
  '/api/public/instagram-image': typeof ApiPublicInstagramImageRoute
  '/api/public/vendor-signup': typeof ApiPublicVendorSignupRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/api/files/stream/$': typeof ApiFilesStreamSplatRoute
  '/api/public/vendor-signup/check': typeof ApiPublicVendorSignupCheckRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/projects/$id/preview/$clientId': typeof AdminProjectsIdPreviewClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor-onboarding': typeof VendorOnboardingRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/login': typeof ClientLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/projects/$id': typeof AdminProjectsIdRouteWithChildren
  '/api/public/instagram-image': typeof ApiPublicInstagramImageRoute
  '/api/public/vendor-signup': typeof ApiPublicVendorSignupRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/api/files/stream/$': typeof ApiFilesStreamSplatRoute
  '/api/public/vendor-signup/check': typeof ApiPublicVendorSignupCheckRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/projects/$id/preview/$clientId': typeof AdminProjectsIdPreviewClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor-onboarding': typeof VendorOnboardingRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/login': typeof ClientLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/projects/$id': typeof AdminProjectsIdRouteWithChildren
  '/api/public/instagram-image': typeof ApiPublicInstagramImageRoute
  '/api/public/vendor-signup': typeof ApiPublicVendorSignupRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/api/files/stream/$': typeof ApiFilesStreamSplatRoute
  '/api/public/vendor-signup/check': typeof ApiPublicVendorSignupCheckRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/projects/$id/preview/$clientId': typeof AdminProjectsIdPreviewClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/vendor-onboarding'
    | '/vendor-signup'
    | '/admin/submissions'
    | '/admin/users'
    | '/client/login'
    | '/email/unsubscribe'
    | '/admin/'
    | '/client/'
    | '/admin/projects/$id'
    | '/api/public/instagram-image'
    | '/api/public/vendor-signup'
    | '/lovable/email/suppression'
    | '/admin/projects/'
    | '/api/files/stream/$'
    | '/api/public/vendor-signup/check'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/projects/$id/preview/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/vendor-onboarding'
    | '/vendor-signup'
    | '/admin/submissions'
    | '/admin/users'
    | '/client/login'
    | '/email/unsubscribe'
    | '/admin'
    | '/client'
    | '/admin/projects/$id'
    | '/api/public/instagram-image'
    | '/api/public/vendor-signup'
    | '/lovable/email/suppression'
    | '/admin/projects'
    | '/api/files/stream/$'
    | '/api/public/vendor-signup/check'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/projects/$id/preview/$clientId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/vendor-onboarding'
    | '/vendor-signup'
    | '/admin/submissions'
    | '/admin/users'
    | '/client/login'
    | '/email/unsubscribe'
    | '/admin/'
    | '/client/'
    | '/admin/projects/$id'
    | '/api/public/instagram-image'
    | '/api/public/vendor-signup'
    | '/lovable/email/suppression'
    | '/admin/projects/'
    | '/api/files/stream/$'
    | '/api/public/vendor-signup/check'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/projects/$id/preview/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendorOnboardingRoute: typeof VendorOnboardingRoute
  VendorSignupRoute: typeof VendorSignupRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ClientLoginRoute: typeof ClientLoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClientIndexRoute: typeof ClientIndexRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRouteWithChildren
  ApiPublicInstagramImageRoute: typeof ApiPublicInstagramImageRoute
  ApiPublicVendorSignupRoute: typeof ApiPublicVendorSignupRouteWithChildren
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  ApiFilesStreamSplatRoute: typeof ApiFilesStreamSplatRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor-signup': {
      id: '/vendor-signup'
      path: '/vendor-signup'
      fullPath: '/vendor-signup'
      preLoaderRoute: typeof VendorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding': {
      id: '/vendor-onboarding'
      path: '/vendor-onboarding'
      fullPath: '/vendor-onboarding'
      preLoaderRoute: typeof VendorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vendor-signup': {
      id: '/api/public/vendor-signup'
      path: '/api/public/vendor-signup'
      fullPath: '/api/public/vendor-signup'
      preLoaderRoute: typeof ApiPublicVendorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-image': {
      id: '/api/public/instagram-image'
      path: '/api/public/instagram-image'
      fullPath: '/api/public/instagram-image'
      preLoaderRoute: typeof ApiPublicInstagramImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vendor-signup/check': {
      id: '/api/public/vendor-signup/check'
      path: '/check'
      fullPath: '/api/public/vendor-signup/check'
      preLoaderRoute: typeof ApiPublicVendorSignupCheckRouteImport
      parentRoute: typeof ApiPublicVendorSignupRoute
    }
    '/api/files/stream/$': {
      id: '/api/files/stream/$'
      path: '/api/files/stream/$'
      fullPath: '/api/files/stream/$'
      preLoaderRoute: typeof ApiFilesStreamSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$id/preview/$clientId': {
      id: '/admin/projects/$id/preview/$clientId'
      path: '/preview/$clientId'
      fullPath: '/admin/projects/$id/preview/$clientId'
      preLoaderRoute: typeof AdminProjectsIdPreviewClientIdRouteImport
      parentRoute: typeof AdminProjectsIdRoute
    }
  }
}

interface AdminProjectsIdRouteChildren {
  AdminProjectsIdPreviewClientIdRoute: typeof AdminProjectsIdPreviewClientIdRoute
}

const AdminProjectsIdRouteChildren: AdminProjectsIdRouteChildren = {
  AdminProjectsIdPreviewClientIdRoute: AdminProjectsIdPreviewClientIdRoute,
}

const AdminProjectsIdRouteWithChildren = AdminProjectsIdRoute._addFileChildren(
  AdminProjectsIdRouteChildren,
)

interface ApiPublicVendorSignupRouteChildren {
  ApiPublicVendorSignupCheckRoute: typeof ApiPublicVendorSignupCheckRoute
}

const ApiPublicVendorSignupRouteChildren: ApiPublicVendorSignupRouteChildren = {
  ApiPublicVendorSignupCheckRoute: ApiPublicVendorSignupCheckRoute,
}

const ApiPublicVendorSignupRouteWithChildren =
  ApiPublicVendorSignupRoute._addFileChildren(
    ApiPublicVendorSignupRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendorOnboardingRoute: VendorOnboardingRoute,
  VendorSignupRoute: VendorSignupRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ClientLoginRoute: ClientLoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  AdminProjectsIdRoute: AdminProjectsIdRouteWithChildren,
  ApiPublicInstagramImageRoute: ApiPublicInstagramImageRoute,
  ApiPublicVendorSignupRoute: ApiPublicVendorSignupRouteWithChildren,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  ApiFilesStreamSplatRoute: ApiFilesStreamSplatRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
