// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Durable storage adapter for Supabase auth.
 *
 * On iPadOS standalone web apps (Add to Home Screen), Safari aggressively
 * evicts localStorage when the app is closed/backgrounded — the user appears
 * "logged out" on every reopen. IndexedDB survives ITP eviction far better.
 *
 * Strategy: write to BOTH localStorage and IndexedDB. On read, prefer
 * localStorage (fast/sync), fall back to IndexedDB and rehydrate localStorage.
 */
const IDB_NAME = 'saffron-auth';
const IDB_STORE = 'kv';

function openIdb(): Promise<IDBDatabase> | null {
  if (typeof indexedDB === 'undefined') return null;
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(IDB_NAME, 1);
    req.onupgradeneeded = () => req.result.createObjectStore(IDB_STORE);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function idbGet(key: string): Promise<string | null> {
  try {
    const dbp = openIdb();
    if (!dbp) return null;
    const db = await dbp;
    return await new Promise<string | null>((resolve) => {
      const tx = db.transaction(IDB_STORE, 'readonly');
      const req = tx.objectStore(IDB_STORE).get(key);
      req.onsuccess = () => resolve((req.result as string | undefined) ?? null);
      req.onerror = () => resolve(null);
    });
  } catch {
    return null;
  }
}

async function idbSet(key: string, value: string): Promise<void> {
  try {
    const dbp = openIdb();
    if (!dbp) return;
    const db = await dbp;
    await new Promise<void>((resolve) => {
      const tx = db.transaction(IDB_STORE, 'readwrite');
      tx.objectStore(IDB_STORE).put(value, key);
      tx.oncomplete = () => resolve();
      tx.onerror = () => resolve();
    });
  } catch {
    /* noop */
  }
}

async function idbDel(key: string): Promise<void> {
  try {
    const dbp = openIdb();
    if (!dbp) return;
    const db = await dbp;
    await new Promise<void>((resolve) => {
      const tx = db.transaction(IDB_STORE, 'readwrite');
      tx.objectStore(IDB_STORE).delete(key);
      tx.oncomplete = () => resolve();
      tx.onerror = () => resolve();
    });
  } catch {
    /* noop */
  }
}

function createDurableStorage() {
  if (typeof window === 'undefined') return undefined;

  // Kick off IndexedDB → localStorage hydration immediately. Supabase's
  // getSession() awaits storage.getItem(), so returning a promise here lets
  // Supabase properly wait for IndexedDB on the very first read after Safari
  // has evicted localStorage (common in iOS PWAs added to home screen).
  const hydrationPromise: Promise<void> = (async () => {
    try {
      const dbp = openIdb();
      if (!dbp) return;
      const db = await dbp;
      const keys: string[] = await new Promise((resolve) => {
        try {
          const tx = db.transaction(IDB_STORE, 'readonly');
          const req = tx.objectStore(IDB_STORE).getAllKeys();
          req.onsuccess = () => {
            const out: string[] = [];
            for (const k of (req.result as IDBValidKey[]) ?? []) {
              if (typeof k === 'string') out.push(k);
            }
            resolve(out);
          };
          req.onerror = () => resolve([]);
        } catch {
          resolve([]);
        }
      });
      for (const key of keys) {
        try {
          if (window.localStorage.getItem(key) == null) {
            const v = await idbGet(key);
            if (v != null) {
              try { window.localStorage.setItem(key, v); } catch { /* quota */ }
            }
          }
        } catch {
          /* noop */
        }
      }
    } catch {
      /* noop */
    }
  })();

  return {
    // Async getItem: Supabase awaits this, so we can safely block on the
    // initial IndexedDB hydration before returning the session.
    getItem: async (key: string): Promise<string | null> => {
      try {
        const v = window.localStorage.getItem(key);
        if (v != null) return v;
      } catch {
        /* noop */
      }
      // Wait for the initial bulk hydration to finish, then re-check localStorage.
      try { await hydrationPromise; } catch { /* noop */ }
      try {
        const v = window.localStorage.getItem(key);
        if (v != null) return v;
      } catch {
        /* noop */
      }
      // Last resort: read this specific key directly from IndexedDB.
      const v = await idbGet(key);
      if (v != null) {
        try { window.localStorage.setItem(key, v); } catch { /* noop */ }
        return v;
      }
      return null;
    },
    setItem: (key: string, value: string) => {
      try { window.localStorage.setItem(key, value); } catch { /* noop */ }
      void idbSet(key, value);
    },
    removeItem: (key: string) => {
      try { window.localStorage.removeItem(key); } catch { /* noop */ }
      void idbDel(key);
    },
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: createDurableStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
